version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h
      - DB_PATH=/app/data/database.sqlite
      - DEFAULT_CHIPS=1000
      - SMALL_BLIND=10
      - BIG_BLIND=20
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/data
    command: npm run dev

volumes:
  backend_data: